#!/usr/bin/env python
from __future__ import print_function
from __future__ import unicode_literals
import argparse
import operator
from chemphysconst import PeriodicTable

program_description = 'Small scripts that returns element details'
parser = argparse.ArgumentParser(description=program_description)

parser.add_argument('input',
                    metavar='atomic symbol',
                    type=str,
                    help='Returns data for this element')
args = parser.parse_args()

PT = PeriodicTable()
element = PT.element(args.input)

element_info = """
  Name:                   {0.name}
  Symbol:                 {0.symbol}
  Number:                 {0.number}
  Period:                 {0.period}
  Group:                  {0.group}
  Atomic Mass:            {0.mass}
  Atomic Weight:          {0.weight:.4f}
  Representing Isotope:   {0.representing_isotope.mass_number}
  Stable:                 {0.is_stable}
  Density:                {0.density} g/cm^3
  Melting Point:          {0.melting_point} K
  Boiling Point:          {0.boiling_point} K
  Electronegativity:      {0.electro_negativity}
  Elemental Abundance:    {0.abundance_crust}  mg/kg""".format(element)

iso_info = """
    Mass Number:          {0.mass_number}
    Atomic Mass:          {0.atomic_mass}
    Abundance:            {0.abundance}"""

print(element_info[1:])

if element.is_stable:
    print('  Stable isotopes:')
    isos = [(iso.abundance, iso.mass_number) for iso in element.isotopes]
    isos.sort(key=operator.itemgetter(0))
    for iso in reversed(isos):
        isotope = element.isotope(iso[1])
        if isotope.abundance > 0.0:
            print (iso_info.format(isotope))
